[package]
name = "prost-wkt-example"
version = "0.4.2"
authors = ["fdeantoni <fdeantoni@gmail.com>"]
edition = "2021"

[dependencies]
prost = "0.12.1"
prost-wkt = { path = ".." }
prost-wkt-types = { path = "../wkt-types" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }

[build-dependencies]
prost-build = "0.12.1"
prost-wkt-build = { path = "../wkt-build" }
