[package]
name = "prost-wkt-types"
version = "0.3.3"
authors = ["fdeantoni <fdeantoni@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/fdeantoni/prost-wkt"
description = "Helper crate for prost to allow JSON serialization and deserialization of Well Known Types."
readme = "../README.md"
documentation = "https://docs.rs/prost-wkt"
keywords = ["protobuf", "serde", "json"]
categories = ["encoding"]
edition = "2018"

[lib]
doctest = false

[features]
default = ["std"]
std = []

[dependencies]
prost-wkt = { version = "0.3.3", path = ".." }
prost = "0.10.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[build-dependencies]
prost = "0.10.0"
prost-types = "0.10.0"
prost-build = "0.10.0"
prost-wkt-build = { version = "0.3.3", path = "../wkt-build" }
